### ISSUE TITLE
Escaping of backslashes in services.yml

### ISSUE THREAD

**Issue by xelan** [RiperFr/Security-ActiveDirectoryBundle#19]
Hi Loic!

While running a system test with Symfony 2.8, I found out that your services.yml can't get parsed due to non-escaped backslashes.

Example:

``` yaml
services:
    riper.security.active.directory.user.provider:
        class: "Riper\Security\ActiveDirectoryBundle\Security\User\AdUserProvider"
        arguments: ["%riper.security.active_directory.settings%", "@riper.security.active.directory.service.adldap", "@translator"]
```

Starting from Symfony YAML 2.8, backslashes in double quotes MUST be escaped [1]. However, in the best practices guide[2], the service class names are used without any quotes at all.

What do you think?

Thanks!

[1] https://github.com/symfony/yaml/blob/master/CHANGELOG.md#280
[2] http://symfony.com/pdf/Symfony_best_practices_2.8.pdf?v=4
